name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - source
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
    - uses: bahmutov/npm-install@v1
    - name: Build and Deploy
      run: yarn && yarn build
    - uses: actions/cache@v1
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-  
    - uses: manyuanrong/setup-ossutil@v1.0
      with:
        # endpoint 可以去oss控制台上查看
        endpoint: "oss-cn-hangzhou.aliyuncs.com"
        # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
    - name: Deply To OSS
      run: ossutil cp docs/.vuepress/dist oss://blog-sonic/ -rf
    - run: |
        curl 'https://oapi.dingtalk.com/robot/send?access_token=66eeb0aa0384e3fb6d237f26b8285f1c8e0812a256ad35ff5acc2da57e8632de' \
           -H 'Content-Type: application/json' \
           -d '{"msgtype": "text",
                "text": {
                     "content": "博客更新了"
                }
          }'

